### ISSUE TITLE
No message on Kafka topic

### ISSUE THREAD

**Issue by wshamim1** [kaiwaehner/kafka-connect-iot-mqtt-connector-example#1]
hi

I was able to load mqtt source with kafka-connect-mqtt.
everything went fine and I see the status of the mqtt source as Running.

ksql-server is [DOWN]
connect is [UP]
kafka-rest is [DOWN]
schema-registry is [UP]
kafka is [UP]
zookeeper is [UP]

confluent status mqtt-source 

{"name":"mqtt-source","connector":{"state":"RUNNING","worker_id":"*****:8083"},"tasks":[{"state":"RUNNING","id":0,"worker_id":"*****:8083"}],"type":"source"}

But I dont see message coming into kafka topic from mqtt topic. how do I enable debugging to see for any error or what could be the issue

**Comment by wshamim1** [comment]
Its working now... thanks for the post

**Comment by kaiwaehner** [comment]
@wilsonshamim Thanks for trying it out. Great that it works now. 

Is there an error or unclear description in the step-by-step guide? If so, I would like to fix it :-) Or was it something else?

**Comment by wshamim1** [comment]
I believe your steps are fine. the issue was mostly with schema registry. It does create an schema with the topicname-key and topicname-value say ["hello-mqtt-kafka-value","hello-mqtt-kafka-key"] when we publish mqtt message.
I had updated listener property schema-registry.properties pointing to server:port where as  the below properties were pointing to localhost in connect-avro-standalone.properties
key.converter.schema.registry.url=
value.converter.schema.registry.url=

**Comment by kaiwaehner** [comment]
Ah okay, thanks. 

Yeah, I should also build a demo with Schema Registry and Avro data.

**Comment by wshamim1** [comment]
I have observed that when I consume a message, it displayes some byte codes along with string. 

    ss
    te
    te
    test

any suggestion on it
