### ISSUE TITLE
problem mapping mosquitto topic to kafka topic

### ISSUE THREAD

**Issue by langalibalele** [kaiwaehner/kafka-connect-iot-mqtt-connector-example#10]
Hello Kai,
in your video Live Demo Video you mention that there is a bug in the kafka/mosquitto topic mapping, that kafka.topic should be left to mqtt. instead of for example mqtt.temperature.
![grafik](https://user-images.githubusercontent.com/13710760/82251876-4e659380-994e-11ea-8d7c-33592009f961.png)
Has this bug been fixed in the meantime? If not, how can I properly map mqtt.topics to kafka.topic? WIth the current solution every mosquitto topic will be classified under the kafka topic mqtt. , which means I cannot differentiate between the sensors in kafka based on their kafka topics.

**Comment by kaiwaehner** [comment]
This was indeed a bug at the time of the video recording. 

This has been fixed long time ago, already. The docs are also up-to-date:
https://docs.confluent.io/current/connect/kafka-connect-mqtt/index.html
