### ISSUE TITLE
Byte Message in mqtt connector

### ISSUE THREAD

**Issue by wshamim1** [kaiwaehner/kafka-connect-iot-mqtt-connector-example#2]
Hi,

I was playing with the mqtt connector. I am seeing byte message
./kafka-console-consumer --bootstrap-server lctcsd1090.merck.com:9092 --topic mqtt. --from-beginning

��ss
��te
��te

I noticed that mqtt.-value schema is having type as bytes. I deleted the schema from schema registry and recreated with string {"subject":"mqtt.-value","version":1,"id":1,"schema":"\"string\""} but I still see the message in bytes.

I even tried StringDeserializer while consuming the message but no luck.

any help

**Comment by kaiwaehner** [comment]
@wilsonshamim Can you please also add how you produce the data and what data you send? 

Then I can take a look and also ask the engineers if needed.

**Comment by wshamim1** [comment]
Thanks for your response.
I tried 2 approach
first using  mosquitto_pub -h 127.0.0.1 -t hello-kafka-topic -m "Hello world"       
Second using mqtt.fx version 1.7.0  message without quotes : test123                

output:
^@^@^@^@^B^VHello world
^@^@^@^@^Btest123

**Comment by kaiwaehner** [comment]
Okay, just realized that you are not exactly using my demo, but using Avro and Schema Registry, right?

Can we get a copy of the connector and worker properties file being used? Or just a copy of the worker log from startup? At a guess maybe you are using Avro for key converter? But need to see config/log [which echoes the config] to be sure.

**Comment by wshamim1** [comment]
After a long struggle I am able to fix it. Its working as expected.

here are my configuration:
source-anonymous.properties 

name=anonymous
tasks.max=1
connector.class=io.confluent.connect.mqtt.MqttSourceConnector
mqtt.server.uri=tcp://localhost:1883
mqtt.topics=temperature
kafka.topics=mqtt



etc/kafka/connect-standalone.properties should have the below:

value.converter=org.apache.kafka.connect.converters.ByteArrayConverter
key.converter=org.apache.kafka.connect.json.JsonConverter
converter.encoding=UTF-8
value.converter.schemas.enable=true

**Comment by shu-bham** [comment]
@kaiwaehner I have  followed your tutorial step-by-step and have not touched any converter configs in etc/kafka/connect-standalone.properties 
Its still showing me byte messages even after trying changes suggested by @wilsonshamim 
![screenshot from 2018-12-08 12-04-12](https://user-images.githubusercontent.com/23572869/49682871-9d649380-fae1-11e8-84fd-d3c4720b4327.png)
