### ISSUE TITLE
Not recieving message on kafka consumer

### ISSUE THREAD

**Issue by shu-bham** [kaiwaehner/kafka-connect-iot-mqtt-connector-example#3]
Hi, I followed your tutorial. I am not able to recieve messages on my kafka-consumer although mosquitto_sub is getting the messsages. Pls help me.

**Comment by kaiwaehner** [comment]
Can you please give more details? 

Did you follow it step-by-step? Which Operating System, Java version, etc.? 

Did you take a look at the logs?

**Comment by shu-bham** [comment]
I am using Ubuntu 18.04, java version "1.8.0_171". I am running both mosquitto and kafka on my local machine.
Could you tell me what logs to check and what should I look in them for checking the working of the mqtt-connector.

**Comment by shu-bham** [comment]
Whats problem with the payload (Order of entering text : "1" to "8")
![screenshot from 2018-11-19 01-49-05](https://user-images.githubusercontent.com/23572869/48677621-8fd08380-eb9d-11e8-8274-ffc62cc8d5cf.png)

**Comment by kaiwaehner** [comment]
@shu-bham Thanks for the details. 

First of all, I refactored the step-by-step guide to make it easier / more clear. I move some stuff to the end which is not needed / not explained well (i.e. how to configure Connect via the "confluent load" command.

Can you please do a "confluent destroy" and start from scratch (using the curl command to configure the MQTT Connector)?

I hope this works now. If not, please see the section "Change log level of Kafka Connect" to take a look at the Connect logs. 

I hope this works now?

**Comment by shu-bham** [comment]
@kaiwaehner Thanks for the reply.
My problem was resolved and I am now able to get messages on my kafka consumer.

I have uploaded a screenshot above, can you tell me why the messages I published via Mosquitto are not the same as shown on kafka-consumer.

**Comment by kaiwaehner** [comment]
@shu-bham Do you have the same problem when you do exactly what I did? Without any changes like -q parameter in mosquitto pub and without changing topic names etc? 

Just want to be sure. I just followed my tutorial again step by step, it does NOT show JSON like your screenshot but just the String:

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/813987/48864931-22ac3080-eddf-11e8-9495-93e7b4526123.png">

**Comment by shu-bham** [comment]
Thanks @kaiwaehner I performed "confluent destroy" and started again and this time its working.
