### ISSUE TITLE
It is proposed to change the kafka-console-consumer topic to mqtt.

### ISSUE THREAD

**Issue by xiaotongwang1** [kaiwaehner/kafka-connect-iot-mqtt-connector-example#5]
$ kafka-console-consumer --bootstrap-server localhost:9092 --topic mqtt.temperature --property print.key=true --from-beginning

-->
$ kafka-console-consumer --bootstrap-server localhost:9092 --topic mqtt. --property print.key=true --from-beginning

**Comment by kaiwaehner** [comment]
I will update my project next week. A new version of MQTT Connector coming before Christmas should fix this.

**Comment by kaiwaehner** [comment]
MQTT Connector 1.1.0 was released (https://www.confluent.io/connector/kafka-connect-mqtt/), including the bugfix for topic mappings.

I updated the example.
