### ISSUE TITLE
Unable to change topic name

### ISSUE THREAD

**Issue by bharat-gera** [kaiwaehner/kafka-connect-iot-mqtt-connector-example#6]
Hi,

While using mqtt kafka connector, I'm able to consume message on topic "mqtt." from MQTT broker but if change my topic name in KC config, I'm unable to consume message from that topic.And noticed that messages are publishing on the same topic "mqtt.". 

I know you have mentioned this as a bug in mqtt kafka connector. Does community provide support for this connector?
Should we go ahead for our production systems?

**Comment by wshamim1** [comment]
Hi

To fix that use kafka.topic instead of kafka.topics

kafka.topic=topic2

**Comment by kaiwaehner** [comment]
This is a bug in current MQTT Connector. 

I will update my project next week. A new version of MQTT Connector coming before Christmas should fix this.

**Comment by bharat-gera** [comment]
Thanks for updating. Will be looking forward for the same.

**Comment by bharat-gera** [comment]
@wilsonshamim kafka.topic is still not working.

**Comment by kaiwaehner** [comment]
@bharat-gera It is not fixed yet as the new MQTT Connector version was not released (expected next week). 

I will update my example after the Connector update. Then it will work.

**Comment by kaiwaehner** [comment]
MQTT Connector 1.1.0 was released (https://www.confluent.io/connector/kafka-connect-mqtt/), including the bugfix for topic mappings.

I updated the example.
